### PR TITLE
(partially?) un-hardcode txz

### LINKED ISSUE #459: PKG_NOCOMPRESS not supported
```
<   Avengence>| [00:53:22] ====>> Stopping 5 builders              
<   Avengence>| [00:53:24] ====>> Creating pkgng repository        
<   Avengence>| [00:53:24] ====>> Error: Unable to extract pkg.    
```

These patches fix some of the problems but are not a complete solution:

```
diff --git src/share/poudriere/common.sh src/share/poudriere/common.sh
index ae3ad018..579b3b9f 100755
--- src/share/poudriere/common.sh
+++ src/share/poudriere/common.sh
@@ -4021,9 +4021,16 @@ ensure_pkg_installed() {
 		cp -f /usr/local/sbin/pkg-static "${mnt}/.p/pkg-static"
 		return 0
 	fi
-	[ -e ${MASTERMNT}/packages/Latest/pkg.txz ] || return 1 #pkg missing
-	injail tar xf /packages/Latest/pkg.txz -C / \
-		-s ",/.*/,.p/,g" "*/pkg-static"
+	if [ -e "${MASTERMNT}/packages/Latest/pkg.txz" ]; then
+		injail tar xf /packages/Latest/pkg.txz -C / \
+		    -s ",/.*/,.p/,g" "*/pkg-static"
+	elif [ -e "${MASTERMNT}/packages/Latest/pkg.tar" ]; then
+		injail tar xf /packages/Latest/pkg.tar -C / \
+		    -s ",/.*/,.p/,g" "*/pkg-static"
+	else
+		# pkg missing
+		return 1
+	fi
 	return 0
 }
 
@@ -5480,6 +5487,12 @@ build_repo() {
 		elif [ -n "${PKG_REPO_SIGNING_KEY}" ]; then
 			sign_pkg pubkey "${PACKAGES}/Latest/pkg.txz"
 		fi
+	elif [ -e "${PACKAGES}/Latest/pkg.tar" ]; then
+		if [ -n "${SIGNING_COMMAND}" ]; then
+			sign_pkg fingerprint "${PACKAGES}/Latest/pkg.tar"
+		elif [ -n "${PKG_REPO_SIGNING_KEY}" ]; then
+			sign_pkg pubkey "${PACKAGES}/Latest/pkg.tar"
+		fi
 	fi
 }
 ```

```
diff --git src/share/poudriere/common.sh src/share/poudriere/common.sh
index ae3ad018..a3a34e0d 100755
--- src/share/poudriere/common.sh
+++ src/share/poudriere/common.sh
@@ -2269,7 +2269,7 @@ jail_start() {
 		# make _SELECTED_OPTIONS='${ALL_OPTIONS:@opt@${PORT_OPTIONS:M${opt}}@} ${MULTI GROUP SINGLE RADIO:L:@otype@${OPTIONS_${otype}:@m@${OPTIONS_${otype}_${m}:@opt@${PORT_OPTIONS:M${opt}}@}@}@}' -V _SELECTED_OPTIONS:O
 	fi
 
-	PKG_EXT="txz"
+	: ${PKG_EXT:="txz"}
 	PKG_BIN="/.p/pkg-static"
 	PKG_ADD="${PKG_BIN} add"
 	PKG_DELETE="${PKG_BIN} delete -y -f"
```

### PR DESCRIPTION
**Pull request by vishwin**
Commits are self-explanatory.

Successfully generated repos with zstd-compressed packages. Should allow `PKG_NOCOMPRESS` to work to fix #459 (although not tested on my end).

### CODE REVIEW

File: src/share/poudriere/common.sh [hunk 1]
```diff
@@ -7699,11 +7699,14 @@ build_repo() {
 	    err 1 "Unable to extract pkg."
 	run_hook pkgrepo sign "${PACKAGES}" "${PKG_REPO_SIGNING_KEY}" \
 	    "${PKG_REPO_FROM_HOST:-no}" "${PKG_REPO_META_FILE}"
+	PKG_META="-m /tmp/pkgmeta"
+	PKG_META_MASTERMNT="-m ${MASTERMNT}/tmp/pkgmeta"
 	if [ -r "${PKG_REPO_META_FILE:-/nonexistent}" ]; then
-		PKG_META="-m /tmp/pkgmeta"
-		PKG_META_MASTERMNT="-m ${MASTERMNT}/tmp/pkgmeta"
```
Comment (bdrewery) [inline src/share/poudriere/common.sh:7703]: This looks unrelated?

File: src/share/poudriere/common.sh [hunk 2]
```diff
@@ -7698,11 +7699,14 @@ build_repo() {
...
 		install -m 0400 "${PKG_REPO_META_FILE}" \
 		    ${MASTERMNT}/tmp/pkgmeta
+	else
+		printf "version = 2;\npacking_format = \"${PKG_EXT}\";\n" > \
```
Comment (bdrewery) [inline src/share/poudriere/common.sh:7708]: @bapt is there any risk to hardcoding this version here or in Makefile.inc1? It's backwards compatible?

Comment (vishwin) [reply src/share/poudriere/common.sh]: Now a moot point with pkg 1.17 accepting mixed compression formats

File: src/share/poudriere/common.sh [hunk 3]
```diff
@@ -3869,14 +3869,15 @@ save_wrkdir() {
...
+	tzst) COMPRESSKEY="-zstd" ;;
 	esac
 	unlink ${tarname}
 
 	port_var_fetch_originspec "${originspec}" \
 	    WRKDIR wrkdir || \
 	    err 1 "Failed to lookup WRKDIR for ${originspec}"
 
-	tar -s ",${mnt}${wrkdir%/*},," -c${COMPRESSKEY}f "${tarname}" \
+	tar -s ",${mnt}${wrkdir%/*},," -cf "${tarname}" -${COMPRESSKEY} \
```
Comment (bdrewery) [inline src/share/poudriere/common.sh:3880]: `tar) COMPRESSKEY=""` means this line turns into `-` at the end. Does that work?
Otherwise this would add the `-` if not blank:
```
${COMPRESSKEY:+-${COMPRESSKEY}}
```

**Review by bdrewery — CHANGES_REQUESTED** [review]

File: src/share/poudriere/common.sh [hunk 4]
```diff
@@ -7791,7 +7792,7 @@ prepare_ports() {
 	if [ $SKIPSANITY -eq 0 ]; then
 		msg "Sanity checking the repository"
 
-		for n in repo.txz digests.txz packagesite.txz; do
+		for n in repo.{pkg,txz} digests.{pkg,txz} packagesite.{pkg,txz}; do
```
Comment (bdrewery) [inline src/share/poudriere/common.sh:7795]: I believe `{pkg,txz}` does not work in `/bin/sh`.

**Review by bdrewery — CHANGES_REQUESTED** [review]

File: src/share/poudriere/common.sh (hunk 4 above)
Comment (vishwin) [reply src/share/poudriere/common.sh]: Indeed.

**Comment by bdrewery** [comment]
Thank you!
