### PR TITLE
Fix fetching packages on FreeBSD 15.0

### LINKED ISSUE #1227: Should e37cf98's addition of -r FreeBSD to the update cmd also have been added to the following, related rquery?
## Prerequisites
- [x] Have you checked for an existing issue describing the issue?

This is more of a question if e37cf9841715392d4397b1f4fc0ebfdbff78a465 was incomplete, prompted by a question on discord that lead to me looking at the code. It added the `-r FreeBSD` in:
```
	if ! JNETNAME="n" injail env ASSUME_ALWAYS_YES=yes \
	    PACKAGESITE="${packagesite:?}" \
	    ${pkg_bin} update -f -r FreeBSD; then
		msg "Package fetch: Not fetching as remote repository is unavailable."
		rm -f "${missing_pkgs}"
		return 0
	fi
```
The following code is:
```
	# Don't trust pkg-update to return its error
	if ! injail ${pkg_bin} rquery -U %n pkg >/dev/null; then
		msg "Package fetch: Failed to fetch package repository."
		rm -f "${missing_pkgs}"
		return 0
	fi
```
Should the rquery also have a `-r FreeBSD` to match?

### LINKED ISSUE #1238: [ERROR] Unhandled error! with -b
Hello,

since the last version (3.4.3) the option “-b” to pull the dependencies from the FreeBSD repository seems to bring poudriere into panic.

Below an snipped of the log (already with -vv)

Reverting back to 3.4.2 seems to workaround the problem at the moment that i needed that option.

```
[00:00:09] Trimming IGNORED and blacklisted ports
[00:00:09] Package fetch: Looking for missing packages to fetch from pkg+http://pkg.FreeBSD.org/${ABI}/latest
[00:00:09] Packge fetch: bootstrapping pkg
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:14:amd64/latest, please wait...
Verifying signature with trusted certificate pkg.freebsd.org.2013102301... done
[143Samd64-default] Installing pkg-2.2.1...
[143Samd64-default] Extracting pkg-2.2.1: 100%
Updating FreeBSD repository catalogue...
[143Samd64-default] Fetching meta.conf: 100%    179 B   0.2kB/s    00:01    
[143Samd64-default] Fetching data.pkg: 100%   10 MiB   2.7MB/s    00:04    
Processing entries: 100%
FreeBSD repository update completed. 36462 packages processed.
FreeBSD is up to date.
[ERROR] Unhandled error!
[00:00:24] Cleaning up
[00:00:24] Unmounting file systems
Exiting with status 1
```

Thank you in advance.

### PR DESCRIPTION
**Pull request by smortex**
Older versions of FreeBSD had a single package repository, named "FreeBSD".  FreeBSD 14.3 introduced a second repository for kernel modules, named "FreeBSD-kmods".  FreeBSD 15.0 add support for managing the base system with packages (aka pkgbase), and to avoid confusion for
users and emphasis they are related to ports and not the base system, the mentioned repositories were respectively renamed "FreeBSD-ports" and "FreeBSD-ports-kmods".

In order to fetch latest packages, poudriere tune the "FreeBSD" repo, and attempts were made to ignore the "FreeBSD-kmods" repository (#1218, #1228), unfortunately with the changes described above in FreeBSD 15, it is broken again.

Since fa68587c67ffb59c1c240d53fb16e73788d06cd3, poudriere disable all official repositories, but that was not done for fetching packages.

Fix this by disabling all known variations of the default FreeBSD repositories there too, and setup a single "Poudriere" repository configured to our wills.

This will allow us to have full control of that repository without being impacted by changes on the FreeBSD side.

Fixes #1227
Fixes #1238

### CODE REVIEW

File: src/share/poudriere/common.sh [hunk 1]
```diff
@@ -2618,12 +2618,25 @@ enter_interactive() {
...
+	        enabled: no;
+	        priority: 100;
+	}
+	FreeBSD-ports: {
+	        enabled: no;
+	        priority: 100;
+	}
+	FreeBSD-ports-kmods: {
+	        enabled: no;
+	        priority: 100;
```
Comment (michael-o) [inline src/share/poudriere/common.sh]: Why not the default priority?

**Comment by smortex** [comment]
Rebased on top of master to fix conflicts, added a fix to disable a repo missing in #1290.

**Comment by bdrewery** [comment]
I like the approach here and plan to merge it after some testing.

**Comment by bdrewery** [comment]
This would fix #1227 and #1238.

**Comment by astralblue** [comment]
Hi, when will 3.4.5 be released with this?

**Comment by bdrewery** [comment]
> Hi, when will 3.4.5 be released with this?

I think it's all in release-3.4 branch already, so a release should be quick to cut. I'll look into it later this week.
