### PR TITLE
Fix issue OSVERSION is empty with pkgbase jail

### LINKED ISSUE #1292: The value of OSVERSION is empty with jails created with pkgbase method
# Environments

- Host OS is 16.0-CURRENT main-n282054-b2b3d2a962eb GENERIC amd64
- Poudriere is commit 27779dbb of main branch

# Describe the bug

If jails are created with pkgbase method, the value of OSVERSION is empty with them as below.

```
# poudriere jail -l
JAILNAME     VERSION         OSVERSION ARCH  METHOD  TIMESTAMP           PATH
135amd64     13.5-RELEASE-p6 1305000   amd64 http    2025-10-23 07:06:25 /usr/local/poudriere/jails/135amd64
143amd64     14.3-RELEASE-p5           amd64 pkgbase 2025-11-25 06:41:57 /usr/local/poudriere/jails/143amd64
143amd64http 14.3-RELEASE-p5 1403000   amd64 http    2025-11-25 06:53:58 /usr/local/poudriere/jails/143amd64http
150amd64     15.0-RC3                  amd64 pkgbase 2025-11-25 06:43:25 /usr/local/poudriere/jails/150amd64
150amd64http 15.0-RC3        1500068   amd64 http    2025-11-25 06:54:25 /usr/local/poudriere/jails/150amd64http
curamd64     16.0-CURRENT              amd64 pkgbase 2025-11-22 04:09:01 /usr/local/poudriere/jails/curamd64
curamd64http 16.0-CURRENT    1600004   amd64 http    2025-11-25 06:55:38 /usr/local/poudriere/jails/curamd64http
# 
```

### PR DESCRIPTION
**Pull request by yasuhirokimura**
If jail is created with pkgbase method, there isn't `/sys` symlink in it.

This fixes #1292.

### CODE REVIEW

File: src/share/poudriere/jail.sh [hunk 1]
```diff
@@ -117,8 +117,8 @@ list_jail() {
 			_jget method ${name} method
 			_jget mnt ${name} mnt
 			_jget timestamp ${name} timestamp || :
-			if [ -r "${mnt}/sys/sys/param.h" ]; then
-				osversion=$(awk '/^\#define[[:blank:]]__FreeBSD_version/ {print $3}' "${mnt}/sys/sys/param.h")
+			if [ -r "${mnt}/usr/src/sys/sys/param.h" ]; then
+				osversion=$(awk '/^\#define[[:blank:]]__FreeBSD_version/ {print $3}' "${mnt}/usr/src/sys/sys/param.h")
```
Comment (bdrewery) [inline src/share/poudriere/jail.sh]: I think it would be safer to check /usr/include/sys/param.h as /usr/src is not required to build much so is often excluded.

**Comment by yasuhirokimura** [comment]
@bdrewery Updated so.

**Review by bdrewery — APPROVED** [review]
